version: '{branch}-{build}'
configuration: Release
clone_folder: C:\Textractor
skip_branch_with_pr: false

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    arch: x64
    platform: x64
    qtbin: msvc2017_64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    arch: x86
    platform: Win32
    qtbin: msvc2017
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    arch: x64
    platform: x64
    qtbin: msvc2017_64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    arch: x86
    platform: Win32
    qtbin: msvc2017
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    arch: x64
    platform: x64
    qtbin: msvc2017_64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    arch: x86
    platform: Win32
    qtbin: msvc2017

before_build:
  - git submodule update --init
  - cd C:\
  - mkdir %arch%
  - cd %arch%
  - ps: $date=Get-Date -Format 'yyMMdd'; [Environment]::SetEnvironmentVariable('BUILD_DATE', $date, 'Process')
  - if not "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (
      py -3 -m pip install --user aqtinstall
    )
  - if not exist "C:\Qt\5.13.2\%qtbin%" (
      if "%arch%"=="x86" (
        py -3 -m aqt install-qt windows desktop 5.13.2 win32_msvc2017 -m qtbase qttools --outputdir C:\Qt\5.13.2\%qtbin%
      ) else if "%arch%"=="x86" (
        py -3 -m aqt install-qt windows desktop 5.13.2 win64_msvc2017_64 -m qtbase qttools --outputdir C:\Qt\5.13.2\%qtbin%
      )
    )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" cmake -G "Visual Studio 15 2017" -A %platform% -DQt5_DIR="C:\Qt\5.13.2\%qtbin%\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE="Release" -DVERSION="" ../Textractor
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" cmake -G "Visual Studio 16 2019" -A %platform% -DQt5_DIR="C:\Qt\5.13.2\%qtbin%\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE="Release" -DVERSION="" ../Textractor
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2022" cmake -G "Visual Studio 17 2022" -A %platform% -DQt5_DIR="C:\Qt\5.13.2\%qtbin%\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE="Release" -DVERSION="" ../Textractor

build:
  project: C:\%arch%\Textractor.sln
  parallel: false
  verbosity: normal

after_build:
  - 7z a Textractor-Alpha%APPVEYOR_BUILD_NUMBER%-%BUILD_DATE%-%arch%.zip C:\%arch%\Release\*
  - appveyor PushArtifact Textractor-Alpha%APPVEYOR_BUILD_NUMBER%-%BUILD_DATE%-%arch%.zip

notifications:
- provider: Email
  to:
  - i@chenx221.cyou
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
