version: '{branch}-{build}'
configuration: Release
clone_folder: C:\Textractor
skip_branch_with_pr: false

build: Script

environment:
  fprefix: Textractor-Qt6
  fprefix2: texthook-Qt6
  vs_gen: "Visual Studio 17 2022"
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

before_build:
  - git submodule update --init
  - ps: $date=Get-Date -Format 'yyMMdd'; [Environment]::SetEnvironmentVariable('BUILD_DATE', $date, 'Process')
  - py -3 -m pip install --user aqtinstall
  - py -3 -m aqt install-qt windows desktop 6.10.3 win64_msvc2022_64 --outputdir C:\Qt -m qt5compat qtwebsockets
  - ps: |
      $url = "https://dl.iloli.one/qt6/Qt_6.10.3_msvc22_32bit.7z"
      $sha256 = "5865677338b54fb59707afb44393c0a105010c0e32af9dc6c00531714b6da294"
      $output = "C:\Qt\Qt_6.10.3_msvc22_32bit.7z"
      Write-Host "Downloading custom Qt 32bit build..."
      (New-Object Net.WebClient).DownloadFile($url, $output)
      if ((Get-FileHash $output -Algorithm SHA256).Hash -ne $sha256) { throw "Hash mismatch!" }
      Write-Host "Extracting..."
      7z x $output -oC:\Qt\6.10.3\

build_script:
  - cd C:\
  - mkdir x86 && mkdir x64

  - cd C:\x86
  - cmake -G "%vs_gen%" -A Win32 -DQt6_DIR="C:\Qt\6.10.3\msvc2022\lib\cmake\Qt6" -DCMAKE_BUILD_TYPE="Release" -DVERSION="" ..\Textractor
  - cmake --build . --config Release -j 1
  - cd C:\x64
  - cmake -G "%vs_gen%" -A x64 -DQt6_DIR="C:\Qt\6.10.3\msvc2022_64\lib\cmake\Qt6" -DCMAKE_BUILD_TYPE="Release" -DVERSION="" ..\Textractor
  - cmake --build . --config Release -j 1

after_build:
  - mkdir C:\textractor-build
  - mkdir C:\textractor-build\x86
  - mkdir C:\textractor-build\x64
  - xcopy C:\Textractor\builds\Release_x86\* C:\textractor-build\x86\ /E /I /Y
  - xcopy C:\Textractor\builds\Release_x64\* C:\textractor-build\x64\ /E /I /Y
  - 7z a %fprefix%-Alpha%APPVEYOR_BUILD_NUMBER%-%BUILD_DATE%.zip C:\textractor-build\*
  - appveyor PushArtifact %fprefix%-Alpha%APPVEYOR_BUILD_NUMBER%-%BUILD_DATE%.zip
  - mkdir C:\texthook
  - mkdir C:\texthook\x86
  - mkdir C:\texthook\x64
  - copy C:\Textractor\builds\Release_x86\texthook.dll C:\texthook\x86\texthook.dll
  - copy C:\Textractor\builds\Release_x64\texthook.dll C:\texthook\x64\texthook.dll
  - 7z a %fprefix2%-Alpha%APPVEYOR_BUILD_NUMBER%-%BUILD_DATE%.zip C:\texthook\*
  - appveyor PushArtifact %fprefix2%-Alpha%APPVEYOR_BUILD_NUMBER%-%BUILD_DATE%.zip

notifications:
- provider: Email
  to:
  - i@chenx221.cyou
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
